### =========================================================================
### get_doi
### =========================================================================
#' Create a DOI for GBIF-derived datasets
#'
#' A lightweight wrapper around \code{rgbif::derived_dataset()} that combines
#' one or more \code{get_gbif()} outputs into a citable derived dataset.
#' 
#' @param gbifs A \code{getGBIF} object or a list of \code{getGBIF} objects.
#' @param title Character string giving the title of the derived dataset.
#' @param description Character string describing the dataset.
#' @param source_url Character string pointing to the location where the
#' derived dataset or workflow is documented.
#' @param user Character string with the GBIF username used to submit the
#' request.
#' @param pwd Character string with the GBIF password used to submit the
#' request.
#' @param ... Additional arguments passed to
#' \code{rgbif::derived_dataset()}.
#' @details See \code{rgbif::derived_dataset()} for GBIF requirements and the
#' structure of the returned metadata.
#' @return The object returned by \code{rgbif::derived_dataset()}, including the
#' DOI request metadata generated by GBIF.
#' @references 
#' Chamberlain, S., Oldoni, D., & Waller, J. (2022). rgbif: interface to the
#' global biodiversity information facility API. 10.5281/zenodo.6023735
#' @seealso The \code{rgbif} package for more general workflows to create GBIF
#' derived datasets and DOIs.
#' @example inst/examples/get_doi_help.R
#' @importFrom rgbif derived_dataset
#' @importFrom methods is
#' @export
get_doi <- function(gbifs = NULL,
				   title = NULL,
				   description = NULL,
				   source_url = "https://example.com/", 
				   user = "",
				   pwd = "",
				   ...) {

  ######################################################
  ### Stop messages
  ######################################################


  # Test input
  if (!(methods::is(gbifs,"getGBIF") || methods::is(gbifs,"list"))) {
  	stop("Given 'gbifs' must be a getGBIF object.")
  }

  # Other checks
  check_character_vector(title, "title")
  check_character_vector(description, "description")
  check_character_vector(source_url, "source_url")
  check_character_vector(user, "user")
  check_character_vector(pwd, "pwd")


  ######################################################
  ### Code
  ######################################################

	# If data.frame, transform in list for code homogenisation
	if (methods::is(gbifs,"getGBIF")) {gbifs <- list(gbifs)}

	# Combine everything
	all.obs <- do.call("rbind", gbifs)

	# Pre-compile a bit
	d.target <- table(all.obs$datasetKey)
	d.summary <- data.frame(
		datasetKey = names(d.target),
		count = as.numeric(d.target)
	)

	# Run the doi function from rgbif
	rgbif::derived_dataset(citation_data = d.summary,
						   title = title,
						   description = description,
						   source_url = source_url,
						   user = user,
						   pwd = pwd,
						   ...)
}
