name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
        sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texinfo ghostscript

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ~/.R/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Install R packages
      run: |
        R -e 'install.packages("devtools")'
        R -e 'install.packages("remotes")'
        R -e 'remotes::install_cran(c("terra", "sf", "rgbif", "CoordinateCleaner", "ClusterR", "FNN", "geometry", "cluster", "rnaturalearth", "mclust", "methods"))'

    - name: Check package
      run: |
        R CMD build .
        R CMD check *tar.gz

    - name: Upload check results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: R-CMD-check-results
        path: check/*.Rcheck

  R-CMD-check-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        brew install udunits gdal geos proj
        brew install mactex-no-gui

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ~/.R/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Install R packages
      run: |
        R -e 'install.packages("devtools")'
        R -e 'install.packages("remotes")'
        R -e 'remotes::install_cran(c("terra", "sf", "rgbif", "CoordinateCleaner", "ClusterR", "FNN", "geometry", "cluster", "rnaturalearth", "mclust", "methods"))'

    - name: Check package
      run: |
        R CMD build .
        R CMD check *tar.gz

    - name: Upload check results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: R-CMD-check-results
        path: check/*.Rcheck
