name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ~/.R/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Install R packages
      run: |
        install.packages('devtools')
        install.packages('remotes')
        remotes::install_cran(c('terra', 'sf', 'rgbif', 'CoordinateCleaner', 'ClusterR', 'FNN', 'geometry', 'cluster', 'rnaturalearth', 'mclust', 'methods'))

    - name: Check package
      run: |
        R CMD build .
        R CMD check *tar.gz

    - name: Upload check results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: R-CMD-check-results
        path: check/*.Rcheck

  R-CMD-check-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        brew install gdal geos proj

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ~/.R/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Install R packages
      run: |
        install.packages('devtools')
        install.packages('remotes')
        remotes::install_cran(c('terra', 'sf', 'rgbif', 'CoordinateCleaner', 'ClusterR', 'FNN', 'geometry', 'cluster', 'rnaturalearth', 'mclust', 'methods'))

    - name: Check package
      run: |
        R CMD build .
        R CMD check *tar.gz

    - name: Upload check results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: R-CMD-check-results
        path: check/*.Rcheck
